---
kind: Job
apiVersion: batch/v1
metadata:
  name: os-job
spec: 
  template:
    spec:
      containers:
      - name: os-container
        image: centos:7
        command: ["bash"]
        args:
        - "-c"
        - "echo 'Hello' ; sleep 60 ; echo 'Bye'"
      restartPolicy: Never
